---
- name: "Hypr | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: hypr_distribution_config

- name: "Hypr | Run {{ ansible_distribution }} Tasks"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: hypr_distribution_config.stat.exists

- name: "Hypr | Configure folder"
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/hypr"
    state: directory

- name: "Hypr | Create symlink to role files directory"
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/hypr"
    state: link
    force: true
