---
- name: "Bat | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/sharkdp/bat/releases/latest
  register: bat_latest_version_json
  changed_when: false

- name: "Bat | Registering Bat Latest Release"
  ansible.builtin.set_fact:
    bat_latest_release: "{{ bat_latest_version_json.json.tag_name }}"

- name: "Bat | Registering Bat Latest Version"
  ansible.builtin.set_fact:
    bat_latest_version: "{{ bat_latest_release.stdout | default('') }}"

- name: "Bat | Getting version information"
  ansible.builtin.command:
    cmd: bat -version
  register: current_bat_version
  changed_when: false
  failed_when: false

- name: "Bat | Edit current_bat_version"
  ansible.builtin.set_fact:
    current_bat_version: "{{ current_bat_version.stdout.split(' ')[-1] | default('') }}"

- name: "Bat | Show current_bat_version debug"
  ansible.builtin.debug:
    var: current_bat_version

- name: "Bat | Show bat_latest_release debug"
  ansible.builtin.debug:
    var: bat_latest_release

- name: "Bat | Install"
  when: bat_latest_release | regex_replace('^.', '') not in current_bat_version|default('')
  block:
    - name: "Bat | Install Bat"
      community.general.pacman:
        name: bat
        state: present
      become: true
