---
- name: Run Arch Tasks
  ansible.builtin.import_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'

- name: "BAT | Configure BAT"
  ansible.builtin.copy:
    src: bat
    dest: "{{ ansible_user_dir }}/.config/"
    mode: "0644"
    directory_mode: "0755"
    force: true